# примеры API-запросов

{{baseUrl}} = https://localhost:8000/api

###

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 091b406af0102042be0ec5cbb7d3204bb0f8f544

{
  "title": " Тумбочка HOFF",
  "description": "Неспешно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/11/
Content-Type: application/json
Authorization: Token 091b406af0102042be0ec5cbb7d3204bb0f8f544

{
  "status": "CLOSED"
}

###

#попытка удалить объявление
DELETE {{baseUrl}}/advertisements/5/
Content-Type: application/json
Authorization: Token 091b406af0102042be0ec5cbb7d3204bb0f8f544

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json


###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2022-11-28
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=DRAFT
Content-Type: application/json

###

# проверка DRAFT для объявления (если анон - драфта нет, если создатель, не видно чужих)
PATCH {{baseUrl}}/advertisements/11/
Content-Type: application/json
Authorization: Token 091b406af0102042be0ec5cbb7d3204bb0f8f544

{
  "status": "DRAFT"
}

###

# добавление объявления в избранное
POST {{baseUrl}}/favorite/
Content-Type: application/json
Authorization: Token 51fe0da07420c7b98052f4fbfb1d2aff3b89193e

{
  "favorite": "True",
  "advertisement": 10
}

###

# просмотр избранного пользователя (по юзеру формируется кверисет)
GET {{baseUrl}}/favorite/
Content-Type: application/json
Authorization: Token 091b406af0102042be0ec5cbb7d3204bb0f8f544


###

# удаление избранного пользователя
DELETE {{baseUrl}}/favorite/6/
Content-Type: application/json
Authorization: Token 091b406af0102042be0ec5cbb7d3204bb0f8f544

