# Generated by Django 4.1.3 on 2022-11-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_options_alter_scope_id_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='id_tag',
            new_name='tag',
        ),
    ]
