# примеры API-запросов

http://localhost:8000/api/v1

###
# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Лимон",
  "description": "Кислейший"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/2/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/2/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=вселенной
Content-Type: application/json

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "левый сток",
  "positions": [
    {
      "product": 4,
      "quantity": 250,
      "price": 120.50
    },
    {
      "product": 5,
      "quantity": 100,
      "price": 180
    }
  ]
}

###

# создаем или обновляем записи на складе
PATCH {{baseUrl}}/stocks/31/
Content-Type: application/json

{
  "positions": [
    {
      "product": 3,
      "quantity": 123,
      "price": 131.80
    },
    {
      "product": 5,
      "quantity": 246,
      "price": 145
    }
  ]
}

###

# поиск складов, где есть определенный продукт (можно искать по id, названию, описанию)
GET {{baseUrl}}/stocks/?products=3&page=1
Content-Type: application/json
